# Generated by Django 4.1.7 on 2023-03-04 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_subscription_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='start_time',
            field=models.BigIntegerField(default=1677894139),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.subscription'),
        ),
    ]
