# Generated by Django 4.1.7 on 2023-03-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_subscription_start_time_alter_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='end_date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.BigIntegerField(default=1677896992),
        ),
    ]
