# Generated by Django 4.1.7 on 2023-03-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_invoice_end_date_alter_invoice_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stop_timer',
            field=models.BigIntegerField(default=1677898179),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.BigIntegerField(default=1677898179),
        ),
    ]
