# Generated by Django 4.1.7 on 2023-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_subscription_stop_timer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.BigIntegerField(default=1677902158),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stop_timer',
            field=models.BigIntegerField(default=1677902158),
        ),
    ]
